### ISSUE TITLE
Create Dialog Window for Graph Input with Validation

### ISSUE THREAD

**Issue by D1mitrii** [D1mitrii/LETI-educational-practice#3]
По нажатию на кнопку

![Image](https://github.com/D1mitrii/LETI-educational-practice/assets/90792387/86ae3006-7b0f-4f50-b3af-4272a91a7d1f)

появляется диалоговое окно с полем для ввода данных в формате
```
"Название вершины 1" x1 y1
...
"Название вершины N" xN yN
"Название вершины i" "Название вершины j" "вес ребра 1"
...
```
 и кнопкой "approve"

Правила валидации:
- Длинна названия вершин в интервале [1, 2].
- Ребро должно исходить и оканчиваться в объявленных ранее вершинах.
- Не должно быть ребер петель.
- Вес ребер >= 0.

**Comment by Popug-s-catcher** [comment]
Succesfully complited!
